# Travis CI build file for Package-Builder.
# Package-Builder runs on OS X and Linux (Ubuntu).

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      # Tested by tests .swift-version
      # env: SWIFT_SNAPSHOT=4.0.3
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.1.3
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04 SWIFT_SNAPSHOT=4.2.1
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:18.04 SWIFT_SNAPSHOT=4.2.1
    - os: osx
      osx_image: xcode9.2
      sudo: required
      # Tested by tests .swift-version
      # env: SWIFT_SNAPSHOT=4.0.3
    - os: osx
      osx_image: xcode9.4
      sudo: required
      env: SWIFT_SNAPSHOT=4.1.2 JAZZY_ELIGIBLE=true
    - os: osx
      osx_image: xcode10.1
      sudo: required
      env: SWIFT_SNAPSHOT=4.2.1
    - os: osx
      osx_image: xcode10.1
      sudo: required
      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT

script:
  # Set up build structure for test projects
  - mv tests/library ../library
  - mv tests/executable ../executable
  - cp -R ./ ../library/Package-Builder
  - cp -R ./ ../executable/Package-Builder
  - cp -R ../executable ../executable-no-swift-version
  - rm ../executable-no-swift-version/.swift-version
  # This tests Package-Builder with a library
  - cd ../library
  - ./Package-Builder/build-package.sh -projectDir $PWD
  # This tests Package-Builder with an executable
  - cd ../executable
  - ./Package-Builder/build-package.sh -projectDir $PWD
  # Test building a package that does not have a .swift-version file
  - cd ../executable-no-swift-version
  - ./Package-Builder/build-package.sh -projectDir $PWD
